### ISSUE TITLE
KeyError: 'Earth'

### ISSUE THREAD

**Issue by yangyang-studio** [galactics/beyond#38]
![mmexport1658054681318](https://user-images.githubusercontent.com/84533790/179395099-8aa69bf6-71f8-4010-a174-513cf6fad465.png)
KeyError: 'Earth'

Hello, what should I do with it？ Looking forward to your reply, thank you

**Comment by galactics** [comment]
Thank you for your issue. I think your problem is due to two distinct issues:

1. The expected config structure for declaring bsp files has changed, but the example file ``jupiter.py`` was not updates accordingly. This is now corrected by 372656faedaeb224214ea428422c8da0a67feffd.
2. The error message is not very clear on what is happening. A dedicated message is now provided, thanks to c729a6e5df8fd26510ad536f3f3a6c74ac3d656b.

By updating your file, to 

I'll mark this as resolved. Don't hesitate to open it again if you have further questions regarding this specific problem

Cheers !
